language: php

php:
    - 5.5
    - 5.6

env:
    - SYMFONY_VERSION="2.6.*"
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"

before_script:
    - composer self-update
    - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
    - composer install --prefer-source

script: bin/phpunit

notifications:
    email:
      - yann@requestlab.fr